CREATE TABLE IF NOT EXISTS TEACHER_SHIFTS
(
    SHIFT_ID   BIGINT,
    TEACHER_ID BIGINT not null
        primary key
);
IF EXISTS (SELECT * FROM TACHER_SHIFTS)
BEGIN
DELETE FROM TEACHER_SHIFTS;
END

INSERT INTO PUBLIC.TEACHER_SHIFTS (SHIFT_ID, TEACHER_ID) VALUES (1, 1);
INSERT INTO PUBLIC.TEACHER_SHIFTS (SHIFT_ID, TEACHER_ID) VALUES (2, 2);
