CREATE TABLE IF NOT EXISTS TEACHER_SUBJECT
(
    TEACHER_ID BIGINT not null,
    SUBJECT_ID BIGINT not null,
    primary key (SUBJECT_ID, TEACHER_ID),
    constraint FK625XNJHA5RS0QQYNXSTHK646K
        foreign key (TEACHER_ID) references TEACHER,
    constraint FKDNHS9KXDLNRVHQ5K111C87PNA
        foreign key (SUBJECT_ID) references SUBJECT
);

-- VACLAV
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (1, 1);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (1, 2);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (1, 3);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (1, 4);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (1, 5);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (1, 9);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (1, 10);
-- JAROSLAV
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (2, 2);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (2, 3);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (2, 4);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (2, 5);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (2, 9);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (2, 10);
-- TOMAS
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (3, 6);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (3, 7);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (3, 8);
-- RITA
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (4, 13);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (4, 14);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (4, 15);
-- GIEDRIUS
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (5, 11);
-- PRANAS
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (6, 12);
-- VICTOR
-- INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (7, 15);