CREATE TABLE IF NOT EXISTS  TEACHER_SHIFTS
(
    SHIFT_ID   BIGINT,
    TEACHER_ID BIGINT not null
        primary key
);

INSERT INTO PUBLIC.TEACHER_SHIFTS (SHIFT_ID, TEACHER_ID) VALUES (2, 1);
INSERT INTO PUBLIC.TEACHER_SHIFTS (SHIFT_ID, TEACHER_ID) VALUES (1, 2);
INSERT INTO PUBLIC.TEACHER_SHIFTS (SHIFT_ID, TEACHER_ID) VALUES (1, 3);
INSERT INTO PUBLIC.TEACHER_SHIFTS (SHIFT_ID, TEACHER_ID) VALUES (1, 4);
INSERT INTO PUBLIC.TEACHER_SHIFTS (SHIFT_ID, TEACHER_ID) VALUES (1, 5);
INSERT INTO PUBLIC.TEACHER_SHIFTS (SHIFT_ID, TEACHER_ID) VALUES (2, 6);
-- INSERT INTO PUBLIC.TEACHER_SHIFTS (SHIFT_ID, TEACHER_ID) VALUES (3, 7);
