create table TEACHER_SUBJECT
(
    TEACHER_ID BIGINT not null,
    SUBJECT_ID BIGINT not null,
    primary key (SUBJECT_ID, TEACHER_ID),
    constraint FK625XNJHA5RS0QQYNXSTHK646K
        foreign key (TEACHER_ID) references TEACHER,
    constraint FKDNHS9KXDLNRVHQ5K111C87PNA
        foreign key (SUBJECT_ID) references SUBJECT
);

INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (1, 1);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (3, 1);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (6, 1);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (7, 1);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (8, 1);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (9, 1);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (10, 1);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (11, 1);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (12, 1);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (13, 1);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (1, 2);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (2, 2);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (1, 3);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (3, 3);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (14, 4);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (16, 4);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (14, 5);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (15, 5);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (14, 6);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (16, 6);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (17, 7);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (19, 7);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (17, 8);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (19, 8);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (17, 9);
INSERT INTO PUBLIC.TEACHER_SUBJECT (TEACHER_ID, SUBJECT_ID) VALUES (18, 9);
