CREATE TABLE IF NOT EXISTS PROGRAM_SUBJECT_HOURS_LIST
(
    PROGRAM_ID            BIGINT not null,
    SUBJECT_HOURS_LIST_ID BIGINT not null
        constraint UK_SBWVQY3DSHRB4CFE7L0RI0UGA
            unique,
    constraint FKFSRYFLJ79VDPD0O9Y457HL8QK
        foreign key (SUBJECT_HOURS_LIST_ID) references SUBJECT_HOURS,
    constraint FKKL6TY5MU07HS2P10PL45J1GPN
        foreign key (PROGRAM_ID) references PROGRAM
);

-- JAVA
INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 1);
INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 2);
INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 3);
INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 4);
INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 5);
INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 6);
INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 7);
INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 8);
INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 9);
INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 10);
INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 11);
INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 12);
INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 13);
INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 14);
-- INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 15);

-- TESTUOTOJAI
-- INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 1);
-- INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 2);
-- INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 3);
-- INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 4);
-- INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 5);
-- INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 6);
-- INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 7);
-- INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 8);
-- INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 13);
-- INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 14);
-- INSERT INTO PUBLIC.PROGRAM_SUBJECT_HOURS_LIST (PROGRAM_ID, SUBJECT_HOURS_LIST_ID) VALUES (1, 15);
