CREATE TABLE IF NOT EXISTS SUBJECT_CLASSROOMS
(
    SUBJECT_ID   BIGINT not null,
    CLASSROOM_ID BIGINT not null,
    primary key (SUBJECT_ID, CLASSROOM_ID),
    constraint FKFBROTNNN49J6SG4AID8LKAGG4
        foreign key (SUBJECT_ID) references SUBJECT,
    constraint FKTAMTR7A4M4JJ881WU02BNQHFF
        foreign key (CLASSROOM_ID) references CLASSROOM
);

-- INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (1, 1);
-- INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (1, 2);
-- INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (2, 1);
-- INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (2, 2);
-- INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (3, 1);
-- INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (3, 2);
