CREATE TABLE IF NOT EXISTS SOME_THING
(
    ID             BIGINT  auto_increment not null
    primary key,
    CREATED_DATE   TIMESTAMP,
    IS_ACTIVE      BOOLEAN,
    MODIFIED_DATE  TIMESTAMP,
    NAME           CHARACTER VARYING(255),
    SCHOOL_YEAR    CHARACTER VARYING(255),
    STUDENT_AMOUNT INTEGER not null,
    PROGRAM_GROUP  BIGINT,
    SHIFT_GROUP    BIGINT,
    constraint FK2OFC6VRD8XPAYCXPYJDTEDYA2
    foreign key (SHIFT_GROUP) references SHIFT,
    constraint FKSV36YD8W4RNVPGRV5DRYK002E
    foreign key (PROGRAM_GROUP) references PROGRAM
    );

INSERT INTO PUBLIC.SOME_THING (IS_ACTIVE , MODIFIED_DATE, NAME, SCHOOL_YEAR, STUDENT_AMOUNT,PROGRAM_GROUP,SHIFT_GROUP) VALUES (TRUE, '2023-03-09 00:00:00.000000', 'Java programuotojai I', '2022', 10, 1, 1);
INSERT INTO PUBLIC.SOME_THING (IS_ACTIVE , MODIFIED_DATE, NAME, SCHOOL_YEAR, STUDENT_AMOUNT,PROGRAM_GROUP,SHIFT_GROUP) VALUES (TRUE, '2023-03-09 00:00:00.000000', 'Java programuotojai II', '2022', 10, 1, 2);
-- INSERT INTO PUBLIC.SOME_THING (IS_ACTIVE , MODIFIED_DATE, NAME, SCHOOL_YEAR, STUDENT_AMOUNT,PROGRAM_GROUP,SHIFT_GROUP) VALUES (TRUE, '2023-03-09 00:00:00.000000', 'Testuotojai (rytas)', '2022', 5, 2, 1);
-- INSERT INTO PUBLIC.SOME_THING (IS_ACTIVE , MODIFIED_DATE, NAME, SCHOOL_YEAR, STUDENT_AMOUNT,PROGRAM_GROUP,SHIFT_GROUP) VALUES (TRUE, '2023-03-09 00:00:00.000000', 'Testuotojai (vakaras)', '2022', 5, 2, 2);
