create table SUBJECT_CLASSROOMS
(
    SUBJECT_ID   BIGINT not null,
    CLASSROOM_ID BIGINT not null,
    primary key (SUBJECT_ID, CLASSROOM_ID),
    constraint FKFBROTNNN49J6SG4AID8LKAGG4
        foreign key (SUBJECT_ID) references SUBJECT,
    constraint FKTAMTR7A4M4JJ881WU02BNQHFF
        foreign key (CLASSROOM_ID) references CLASSROOM
);

INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (1, 1);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (1, 2);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (2, 1);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (2, 2);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (3, 1);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (3, 2);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (4, 52);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (4, 53);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (5, 52);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (5, 53);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (6, 52);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (6, 53);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (7, 102);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (7, 103);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (8, 102);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (8, 103);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (9, 102);
INSERT INTO PUBLIC.SUBJECT_CLASSROOMS (SUBJECT_ID, CLASSROOM_ID) VALUES (9, 103);
