CREATE TABLE schedule
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id      BIGINT,
    school_year   VARCHAR(255),
    semester      VARCHAR(255),
    date_from     date                                    NOT NULL,
    date_until    date                                    NOT NULL,
    active        BOOLEAN                                 NOT NULL,
    created_date  TIMESTAMP,
    modified_date TIMESTAMP,
    CONSTRAINT pk_schedule PRIMARY KEY (id)
);

-- CREATE TABLE schedule_working_days
-- (
--     schedule_id     BIGINT NOT NULL,
--     working_days_id BIGINT NOT NULL,
--     CONSTRAINT pk_schedule_workingdays PRIMARY KEY (schedule_id, working_days_id)
-- );

-- CREATE TABLE subject_unassigned_time
-- (
--     schedule_id     BIGINT NOT NULL,
--     unassigned_time INT,
--     subject_id      BIGINT NOT NULL,
--     CONSTRAINT pk_subject_unassigned_time PRIMARY KEY (schedule_id, subject_id)
-- );
--
-- ALTER TABLE schedule_working_days
--     ADD CONSTRAINT uc_schedule_working_days_workingdays UNIQUE (working_days_id);
--
-- ALTER TABLE schedule
--     ADD CONSTRAINT FK_SCHEDULE_ON_GROUP FOREIGN KEY (group_id) REFERENCES some_thing (id);
--
-- ALTER TABLE schedule_working_days
--     ADD CONSTRAINT fk_schworday_on_schedule FOREIGN KEY (schedule_id) REFERENCES schedule (id);
--
-- ALTER TABLE schedule_working_days
--     ADD CONSTRAINT fk_schworday_on_work_day FOREIGN KEY (working_days_id) REFERENCES work_day (id);
--
-- ALTER TABLE subject_unassigned_time
--     ADD CONSTRAINT fk_subject_unassigned_time_on_schedule FOREIGN KEY (schedule_id) REFERENCES schedule (id);

INSERT INTO PUBLIC.schedule (ACTIVE,CREATED_DATE,DATE_FROM,DATE_UNTIL,MODIFIED_DATE,SCHOOL_YEAR,SEMESTER,GROUP_ID)
VALUES (TRUE,'2023-03-20 15:27:09.562104','2023-03-20','2023-03-25','2023-03-20 15:27:09.562104','2023','Pirmas', 1 );
INSERT INTO PUBLIC.schedule (ACTIVE,CREATED_DATE,DATE_FROM,DATE_UNTIL,MODIFIED_DATE,SCHOOL_YEAR,SEMESTER,GROUP_ID)
VALUES (TRUE,'2023-03-20 15:28:09.562104','2023-03-27','2023-03-31','2023-03-20 15:28:09.562104','2023','Antras', 1 );
