CREATE TABLE IF NOT EXISTS schedule
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id      BIGINT,
    school_year   VARCHAR(255),
    semester      VARCHAR(255),
    date_from     date                                    NOT NULL,
    date_until    date                                    NOT NULL,
    active        BOOLEAN                                 NOT NULL,
    has_conflicts  BOOLEAN NOT NULL,
    created_date  TIMESTAMP,
    modified_date TIMESTAMP,
    CONSTRAINT pk_schedule PRIMARY KEY (id)
);

-- INSERT INTO PUBLIC.schedule (ACTIVE, HAS_CONFLICTS, CREATED_DATE,DATE_FROM,DATE_UNTIL,MODIFIED_DATE,SCHOOL_YEAR,SEMESTER,GROUP_ID)
-- VALUES (TRUE,FALSE,'2023-03-20 15:27:09.562104','2023-03-20','2023-03-25','2023-03-20 15:27:09.562104','2023','Pirmas', 1 );
-- INSERT INTO PUBLIC.schedule (ACTIVE, HAS_CONFLICTS, CREATED_DATE,DATE_FROM,DATE_UNTIL,MODIFIED_DATE,SCHOOL_YEAR,SEMESTER,GROUP_ID)
-- VALUES (TRUE, FALSE, '2023-03-20 15:28:09.562104','2023-03-27','2023-03-31','2023-03-20 15:28:09.562104','2023','Antras', 1 );
