create table CONTACT
(
    CONTACT_ID   BIGINT auto_increment
        primary key,
    TYPE         SMALLINT not null,
    CONTACT_BODY CHARACTER VARYING(255),
    TEACHER_ID   BIGINT   not null,
    constraint FKK18S44KMACPSN4BQ7BAJ6JH3L
        foreign key (TEACHER_ID) references TEACHER
            on delete cascade
);

INSERT INTO PUBLIC.CONTACT (TYPE, CONTACT_BODY, TEACHER_ID) VALUES (2, 'Teams@1', 1);
INSERT INTO PUBLIC.CONTACT (TYPE, CONTACT_BODY, TEACHER_ID) VALUES (3, 'Teams1', 1);
INSERT INTO PUBLIC.CONTACT (TYPE, CONTACT_BODY, TEACHER_ID) VALUES (1, 'Mail@1', 1);
INSERT INTO PUBLIC.CONTACT (TYPE, CONTACT_BODY, TEACHER_ID) VALUES (0, '8 000 11111', 1);
INSERT INTO PUBLIC.CONTACT (TYPE, CONTACT_BODY, TEACHER_ID) VALUES (0, '800022222', 3);
INSERT INTO PUBLIC.CONTACT (TYPE, CONTACT_BODY, TEACHER_ID) VALUES (1, 'Mail@3', 3);
INSERT INTO PUBLIC.CONTACT (TYPE, CONTACT_BODY, TEACHER_ID) VALUES (2, 'Teams@3', 3);
INSERT INTO PUBLIC.CONTACT (TYPE, CONTACT_BODY, TEACHER_ID) VALUES (3, 'Teams3', 3);
INSERT INTO PUBLIC.CONTACT (TYPE, CONTACT_BODY, TEACHER_ID) VALUES (0, '800022222', 2);
INSERT INTO PUBLIC.CONTACT (TYPE, CONTACT_BODY, TEACHER_ID) VALUES (1, 'Mail@h.lt', 2);
INSERT INTO PUBLIC.CONTACT (TYPE, CONTACT_BODY, TEACHER_ID) VALUES (2, 'Teams@2.lt', 2);
INSERT INTO PUBLIC.CONTACT (TYPE, CONTACT_BODY, TEACHER_ID) VALUES (3, 'Teams2', 2);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (65, 0, '897452652', 4);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (66, 1, 'rugebuge@yahoo.com', 4);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (67, 2, 'rugebuge@yahoo.com', 4);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (68, 3, 'sdfafa', 4);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (69, 0, '897452652', 5);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (70, 1, 'rugebuge@yahoo.com', 5);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (71, 2, 'rugebuge@yahoo.com', 5);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (72, 3, 'sdfafa', 5);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (73, 0, '866611111', 6);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (74, 1, 'skldjf@dlkjdl.lt', 6);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (75, 2, 'skldjf@dlkjdl.lt', 6);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (76, 3, 'hjfgsjhf', 6);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (77, 0, '866611112', 7);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (78, 1, 'skldjf@dlkjdl.lt', 7);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (79, 2, 'skldjf@dlkjdl.lt', 7);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (80, 3, 'hjfgsjhf', 7);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (81, 0, '866611113', 8);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (82, 1, 'skldjf@dlkjdl.lt', 8);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (83, 2, 'skldjf@dlkjdl.lt', 8);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (84, 3, 'hjfgsjhf', 8);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (85, 0, '866611134', 9);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (86, 1, 'skldjf@dlkjdl.lt', 9);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (87, 2, 'skldjf@dlkjdl.lt', 9);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (88, 3, 'hjfgsjhf', 9);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (89, 0, '866611135', 10);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (90, 1, 'skldjf@dlkjdl.lt', 10);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (91, 2, 'skldjf@dlkjdl.lt', 10);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (92, 3, 'hjfgsjhf', 10);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (93, 0, '866651135', 11);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (94, 1, 'skldjf@dlkjdl.lt', 11);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (95, 2, 'skldjf@dlkjdl.lt', 11);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (96, 3, 'hjfgsjhf', 11);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (97, 0, '866651135', 12);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (98, 1, 'skldjf@dlkjdl.lt', 12);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (99, 2, 'skldjf@dlkjdl.lt', 12);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (100, 3, 'hjfgsjhf', 12);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (101, 0, '866651535', 13);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (102, 1, 'skldjf@dlkjdl.lt', 13);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (103, 2, 'skldjf@dlkjdl.lt', 13);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (104, 3, 'hjfgsjhf', 13);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (105, 2, 'Teams@1', 14);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (106, 3, 'Teams1', 14);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (107, 1, 'Mail@1', 14);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (108, 0, '8 000 11111', 14);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (109, 2, 'Teams@2', 15);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (110, 3, 'Teams2', 15);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (111, 1, 'Mail@2', 15);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (112, 0, '8 000 22222', 15);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (113, 2, 'Teams@3', 16);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (114, 3, 'Teams3', 16);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (115, 1, 'Mail@3', 16);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (116, 0, '8 000 33333', 16);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (117, 2, 'Teams@1', 17);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (118, 3, 'Teams1', 17);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (119, 1, 'Mail@1', 17);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (120, 0, '8 000 11111', 17);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (121, 2, 'Teams@2', 18);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (122, 3, 'Teams2', 18);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (123, 1, 'Mail@2', 18);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (124, 0, '8 000 22222', 18);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (125, 2, 'Teams@3', 19);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (126, 3, 'Teams3', 19);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (127, 1, 'Mail@3', 19);
-- INSERT INTO PUBLIC.CONTACT (CONTACT_ID, TYPE, CONTACT_BODY, TEACHER_ID) VALUES (128, 0, '8 000 33333', 19);
